CapitanAmerica/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include(('home.urls','home'),namespace='home')),
    path('admin/', admin.site.urls),
    path('aliado/',include(('aliado.urls','aliado'),namespace='aliado')),
    path('patrocinador/',include(('patrocinador.urls','patrocinador'),namespace='patrocinador')),

]

aliado/urls.py
from django.urls import include, path
from aliado.views import ListarAliados, InsertarAliados, EditarAliado, EliminarAliado

urlpatterns = [
    path('aliado/list',ListarAliados.as_view(),name='listar_aliados'),
    path('aliado/new',InsertarAliados.as_view(),name='insertar_aliado'),
    path('aliado/edit<int:pk>',EditarAliado.as_view(),name='editar_aliado'),
    path('aliado/delete<int:pk>',EliminarAliado.as_view(),name='eliminar_aliado'),
]

patrocinador/urls.py
from django.urls import path, include
from patrocinador.views import ListarPatrocinador, InsertarPatrocinador, EditarPatrocinador, EliminarPatrocinador

urlpatterns=[
    path('patrocinador/list',ListarPatrocinador.as_view(),name="listar_patrocinador"),
    path('patrocinador/new',InsertarPatrocinador.as_view(),name="insertar_patrocinador"),
    path('patrocinador/edit<int:pk>',EditarPatrocinador.as_view(),name="editar_patrocinador"),
    path('patrocinador/delete<int:pk>',EliminarPatrocinador.as_view(),name="eliminar_patrocinador"),
]

aliado/models.py
from django.db import models

# Create your models here.
class Aliado(models.Model):
    id = models.IntegerField( primary_key=True)
    
    nombre = models.CharField(
        max_length=100,
    )


    def __str__(self):
        return '{}'.format(self.nombre)
    

    def save(self):
        
        super(Aliado, self).save()

    class Meta:
        verbose_name_plural = "Aliados"

patrocinador/models.py
from django.db import models

# Create your models here.
class Patrocinador(models.Model):
    id = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    dinero = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.nombre)
    

    def save(self):
        
        super(Patrocinador, self).save()

    class Meta:
        verbose_name_plural = "Patrocinadores"

aliado/forms.py
from django import forms
from aliado.models import Aliado
class AliadoForm(forms.ModelForm):
    class Meta:
        model=Aliado

        fields=['id','nombre']
        labels={'Id': 'Id del aliado'}
        widget={'Id':forms.TextInput()}
        labels={'Nombre':'Nombre del Aliado'}
        widget={'Nombre':forms.TextInput()}
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

patrocinador/forms.py
from django import forms
from patrocinador.models import Patrocinador
class PatrocinadorForm(forms.ModelForm):
    class Meta:
        model=Patrocinador

        fields=['id','nombre','dinero']
        labels={'Id': 'Id del patrocinador'}
        widget={'Id':forms.TextInput()}
        labels={'Nombre':'Nombre del patrocinador'}
        widget={'Nombre':forms.TextInput()}
        labels={'Dinero': 'Dinero del patrocinador'}
        widget={'Dinero':forms.TextInput()}
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

aliado/views.py
from django.shortcuts import render
from aliado.models import Aliado
from django.views import generic
from aliado.forms import AliadoForm
from django.urls import reverse_lazy
from django.http import HttpResponse
# Create your views here.
class ListarAliados(generic.ListView):
    model=Aliado
    template_name="aliado/listar_aliados.html"
    context_object_name="cosa"

class InsertarAliados(generic.CreateView):
    model=Aliado
    template_name="aliado/insertar_aliado.html"
    context_object_name="obj"
    form_class=AliadoForm
    success_url=reverse_lazy("aliado:listar_aliados")

class EditarAliado(generic.UpdateView):
    model=Aliado
    template_name="aliado/insertar_aliado.html"
    context_object_name="obj"
    form_class=AliadoForm
    success_url=reverse_lazy("aliado:listar_aliados")

class EliminarAliado(generic.DeleteView):
    model=Aliado
    template_name="aliado/eliminar_aliado.html"
    context_object_name="obj"
    form_class=AliadoForm
    success_url=reverse_lazy("aliado:listar_aliados")

patrocinador/views.py
from django.shortcuts import render
from django.views import generic
from patrocinador.models import Patrocinador
from patrocinador.forms import PatrocinadorForm
from django.urls import reverse_lazy
# Create your views here.

class ListarPatrocinador(generic.ListView):
    model=Patrocinador
    template_name="patrocinador/listar_patrocinador.html"
    context_object_name="obj"
class InsertarPatrocinador(generic.CreateView):
    model=Patrocinador
    template_name="patrocinador/insertar_patrocinador.html"
    context_object_name="obj"
    form_class= PatrocinadorForm
    success_url= reverse_lazy('patrocinador:listar_patrocinador')
class EditarPatrocinador(generic.UpdateView):
    model=Patrocinador
    template_name="patrocinador/insertar_patrocinador.html"
    context_object_name="obj"
    form_class= PatrocinadorForm
    success_url= reverse_lazy('patrocinador:listar_patrocinador')
class EliminarPatrocinador(generic.DeleteView):
    model=Patrocinador
    template_name="patrocinador/eliminar_patrocinador.html"
    context_object_name="obj"
    form_class= PatrocinadorForm
    success_url= reverse_lazy('patrocinador:listar_patrocinador')

templates/base/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title> {% block head_title %}
    Capitan America
    {% endblock head_title %}
  </title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbars/">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="navbar.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

</head>

<body>



  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Misiones</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="#">Lista</a>
              <a class="dropdown-item" href="#">Insertar Mision</a>
              <a class="dropdown-item" href="#">Imprimir Mision</a>
            </div>
            </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Patrocinadores</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="{% url 'patrocinador:listar_patrocinador' %}">Lista</a>
              <a class="dropdown-item" href="{% url 'patrocinador:insertar_patrocinador' %}">Insertar Patrocinador</a>
              <a class="dropdown-item" href="#">Imprimir Patrocinador</a>
            </div>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Compañeros de Equipo</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="#">Lista</a>
              <a class="dropdown-item" href="#">Insertar Compañero de Equipo</a>
              <a class="dropdown-item" href="#">Imprimir Compañero de Equipo</a>
            </div>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Aliados</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="{% url 'aliado:listar_aliados' %}">Lista</a>
              <a class="dropdown-item" href="{% url 'aliado:insertar_aliado' %}">Insertar Aliados</a>
              <a class="dropdown-item" href="#">Imprimir Aliados</a>
            </div>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Enemigos</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="#">Lista</a>
              <a class="dropdown-item" href="#">Insertar Enemigos</a>
              <a class="dropdown-item" href="#">Imprimir Enemigos</a>
            </div>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Personas Salvadas</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="#">Lista</a>
              <a class="dropdown-item" href="#">Insertar Personas Salvadas</a>
              <a class="dropdown-item" href="#">Imprimir Personas Salvadas</a>
            </div>
            </li>
            </div>
          </li>
        </ul>

      </div>
    </div>
  </nav>
  {% block contenido %}Se puede cambiar{% endblock contenido %}




  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
</body>

</html>